"""Pipeline templates (spec section 56).

    repository detected -> template selected -> parameters populated -> validated

The LLM never writes pipeline code. Stages come from the repository's own
allowlisted commands (forgeflow.yaml or detection); every command is validated
and every value is escaped before it is placed into the Groovy script.
"""

from __future__ import annotations

import re
import shlex
from dataclasses import dataclass, field
from pathlib import Path

from forgeflow.core.errors import ValidationFailed
from forgeflow.tools.git.client import validate_sha
from forgeflow.tools.shell.commands import detect_commands, validate_command

STAGE_ORDER = (
    ("setup", "Setup"),
    ("lint", "Lint"),
    ("typecheck", "Typecheck"),
    ("test", "Test"),
    ("build", "Build"),
)
_REPO_RE = re.compile(r"^[A-Za-z0-9._-]{1,100}$")


@dataclass
class PipelineSpec:
    repository: str
    commit: str
    stages: list[tuple[str, list[str]]] = field(default_factory=list)

    @property
    def job_name(self) -> str:
        return f"forgeflow-{self.repository}"


def build_pipeline_spec(worktree: Path, repository: str, commit: str) -> PipelineSpec:
    if not _REPO_RE.match(repository):
        raise ValidationFailed(f"repository name not allowed in a pipeline: {repository!r}")
    validate_sha(commit)
    commands = detect_commands(worktree)
    stages = []
    for kind, title in STAGE_ORDER:
        cmds = commands.get(kind, [])
        for cmd in cmds:
            validate_command(cmd)
        if cmds:
            stages.append((title, cmds))
    if not stages:
        raise ValidationFailed(
            "no CI commands found: add a forgeflow.yaml with test/lint/build commands"
        )
    return PipelineSpec(repository=repository, commit=commit, stages=stages)


def _groovy(value: str) -> str:
    """Single-quoted Groovy string literal (no interpolation)."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_jenkinsfile(spec: PipelineSpec, repos_root: str) -> str:
    source = f"{repos_root.rstrip('/')}/{spec.repository}"
    lines = [
        "// Generated by ForgeFlow from a validated template. Do not edit by hand.",
        "pipeline {",
        "  agent any",
        "  options { timestamps(); timeout(time: 30, unit: 'MINUTES'); disableConcurrentBuilds() }",
        "  environment { CI = 'true' }",
        "  stages {",
        "    stage('Checkout') {",
        "      steps {",
        "        deleteDir()",
        f"        sh {_groovy(f'git clone --quiet --no-checkout {shlex.quote(source)} src')}",
        f"        sh {_groovy(f'git -C src checkout --quiet --detach {spec.commit}')}",
        "      }",
        "    }",
    ]
    for title, commands in spec.stages:
        lines += [f"    stage({_groovy(title)}) {{", "      steps {", "        dir('src') {"]
        lines += [f"          sh {_groovy(cmd)}" for cmd in commands]
        lines += ["        }", "      }", "    }"]
    lines += ["  }", "}"]
    return "\n".join(lines) + "\n"
